#r "nuget: HalfLife.UnifiedSdk.Utilities, 0.1.3"
#r "nuget: System.CommandLine, 2.0.0-beta3.22114.1"

#load "../CommonScripts.csx"
#load "Packager.csx"

#nullable enable

using HalfLife.UnifiedSdk.Utilities.Tools;
using System.CommandLine;

// Get the name of the mod directory.
static readonly string AbsoluteModDirectory = Path.GetDirectoryName(Path.GetDirectoryName(GetScriptFolder()))
	?? throw new InvalidOperationException("Couldn't get root directory");
static readonly string ModDirectory = Path.GetFileNameWithoutExtension(AbsoluteModDirectory);

// Move to Half-Life directory.
Environment.CurrentDirectory = Path.GetDirectoryName(AbsoluteModDirectory) ?? throw new InvalidOperationException("Couldn't get game directory");

static string MakeModPath(string path) => Path.Combine(ModDirectory, path);

/// <summary>
/// List of files and directories to package.
/// All scripts are also included for others to use.
/// Filenames ending with ".install" will be renamed to remove this extension after being added to the archive.
/// Files specific to only some of the games should be listed as well. The packager will skip any that don't exist.
/// </summary>
static readonly IEnumerable<string> PackageFiles = new[]
{
	Path.Combine("cl_dlls", "client.dll"),
	Path.Combine("dlls", "hl.dll"),
	"delta.lst",
	"game.ico",
	"game.tga",
	"game_big.tga",
	"liblist.gam",
	"README.txt",
	"skill.cfg",
	"settings.scr.install",
	"user.scr.install",
	"titles.txt",
	"installer",
	Path.Combine("maps", "graphs"),
	"models",
	"resource",
	"scripts"
}.Select(MakeModPath)
//Include content directories if they exist.
.Concat(ModUtilities.AllPublicModDirectorySuffixes
	.Select(s => ModUtilities.FormatModDirectory(ModDirectory, s))
	.Where(Directory.Exists));

// Files to exclude from the archive.
static readonly IEnumerable<string> PackageFilesExclusionList = new[]
{
	// Exclude player model image (autogenerated by game).
	Path.Combine("models", "player", "remapped.bmp"),
	// Exclude nuget configuration file. Only used for referencing dev packages.
	Path.Combine("scripts", "nuget.config"),
	// Exclude the VS Code directory. The contents are available on the wiki if modders need them.
	Path.Combine("scripts" ,"installer", ".vscode"),
	Path.Combine("scripts", "packager", ".vscode"),
	// Exclude omnisharp configuration files.
	Path.Combine("scripts", "installer", "omnisharp.json"),
	Path.Combine("scripts", "packager", "omnisharp.json")
}.Select(MakeModPath);

// Command line setup.
var gameToInstallOption = new Option<string>(
		"--package-name",
		description: "Name of the package to create");

var rootCommand = new RootCommand("Half-Life game packager")
{
	gameToInstallOption
};

rootCommand.SetHandler((string packageName) =>
{
	using var packager = new Packager(packageName, PackageFilesExclusionList);
	packager.AddFiles(PackageFiles);
}, gameToInstallOption);

return rootCommand.Invoke(Args.ToArray());
